blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/felixgeelhaar/fortify-ts/discussions/new?category=q-a
    about: Ask questions and get help from the community
  - name: Documentation Issue
    url: https://github.com/felixgeelhaar/fortify-ts/issues/new?labels=documentation
    about: Report issues with documentation
